python 3 updates
pyeve/eve pull request #1493
Opened 2022-11-03 07:05 UTC by marksmayo

and some simplifications of conditional statements.

2022-11-08 10:58 UTC, nicolaiarocci requested changes

2022-11-08 10:58 UTC, nicolaiarocci commented on eve/io/mongo/__init__.py
> +from eve.io.mongo.media import GridFSMediaStorage
tests are failing because of this line. If you move it back to the bottom, they'll pass (imports order is important in this case.)

2022-11-10 09:38 UTC, merged

2022-11-10 09:39 UTC, nicolaiarocci commented
alright i went ahead and applied the fix myself. Thanks for your contribution!

2022-11-28 01:48 UTC, marksmayo commented
@nicolaiarocci sorry for the delayed response. Thanks for sorting that!